### PR TITLE
Added audio (wav, tr) reader classes and libs

### PR DESCRIPTION
**Pull request by mXaln**
This change is [Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10)

### CODE REVIEW

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

*[a discussion](https://reviewable.io/reviews/bible-translation-tools/maui/10#-MDv4R3FCbDP0Y4x9a7u:-MDv4R3HCZFipBbd4ZdC:b-l7h6qe) (no related file):*
I don't really like the idea of pulling the audio code out and committing the source files here. I'm working with Dan on creating our own maven repository and I'm going to get the wav package published as a library that you can import.

We'll do the same for aoh and move away from jitpack. Hopefully self-hosting will allow us to publish libraries and get the changes imported asap, which has been frustrating the in past especially with jitpack.

---
___
*[common/src/main/kotlin/org/bibletranslationtools/common/audio/Metadata.kt, line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/maui/10#-MDv5-O-0PJhw1sd-ojx:-MDv5-O-0PJhw1sd-ojy:bkruufh) ([raw file](https://github.com/bible-translation-tools/maui/blob/43582c0223d526f66187d00d081d576bb526a575/common/src/main/kotlin/org/bibletranslationtools/common/audio/Metadata.kt#L8)):*
> ```Kotlin
> import com.fasterxml.jackson.databind.annotation.JsonSerialize
> 
> data class Metadata(
> ```


Let's name this BttrMetadata since it's associated with bttr specifically

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

*[a discussion](https://reviewable.io/reviews/bible-translation-tools/maui/10#-MDv4R3FCbDP0Y4x9a7u:-MDyKA6a33T3X-KZHKM-:bncjnk7) (no related file):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

I don't really like the idea of pulling the audio code out and committing the source files here. I'm working with Dan on creating our own maven repository and I'm going to get the wav package published as a library that you can import.

We'll do the same for aoh and move away from jitpack. Hopefully self-hosting will allow us to publish libraries and get the changes imported asap, which has been frustrating the in past especially with jitpack.
</blockquote></details>

what should should I do for now?

---

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/audio/Metadata.kt, line 8 at r1](https://reviewable.io/reviews/bible-translation-tools/maui/10#-MDv5-O-0PJhw1sd-ojx:-MDyL-Er2x7-qVFev2Zv:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/43582c0223d526f66187d00d081d576bb526a575/common/src/main/kotlin/org/bibletranslationtools/common/audio/Metadata.kt#L8)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

Let's name this BttrMetadata since it's associated with bttr specifically
</blockquote></details>

Done.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @jsarabia and @mXaln)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/audio/BttrChunk.kt, line 74 at r3](https://reviewable.io/reviews/bible-translation-tools/maui/10#-MF5n8EO3TpE3qRyWlk2:-MF5n8EP-LiH3-ueggJW:b-x9ccvj) ([raw file](https://github.com/bible-translation-tools/maui/blob/ad23f1058ae86ec4aae2f2c18118a2515b8394f3/common/src/main/kotlin/org/bibletranslationtools/common/audio/BttrChunk.kt#L74)):*
> ```Kotlin
> 
>         // Skip List Chunks that are not subtype "INFO"
>         if (chunk.remaining() < CHUNK_LABEL_SIZE || INFO_LABEL != chunk.getText(CHUNK_LABEL_SIZE)) {
> ```

can you assign the two cases to variables to reduce the line length and make this a little more readable?

**Review by mXaln — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @jsarabia)

___
*[common/src/main/kotlin/org/bibletranslationtools/common/audio/BttrChunk.kt, line 74 at r3](https://reviewable.io/reviews/bible-translation-tools/maui/10#-MF5n8EO3TpE3qRyWlk2:-MF5sHHdD5O5mR6-p-GW:b-896fix) ([raw file](https://github.com/bible-translation-tools/maui/blob/ad23f1058ae86ec4aae2f2c18118a2515b8394f3/common/src/main/kotlin/org/bibletranslationtools/common/audio/BttrChunk.kt#L74)):*
<details><summary><i>Previously, jsarabia (Joe) wrote…</i></summary><blockquote>

can you assign the two cases to variables to reduce the line length and make this a little more readable?
</blockquote></details>

Done.

**Review by jsarabia — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bible-translation-tools/maui/10#-:-MF6OH1K0k4oiyaXLvOw:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved

**Pull request merged**
